# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Ibrahim Yousre
tagline:          'Java developer'
description:      'I am passionate about programming and software development. My main focus is java'
url:              'https://ibrahimyousre.github.com'
baseurl:          '/'

author:
  name:           'Ibrahim Yousre'
  url:            https://github.com/IbrahimYousre

paginate:         5

plugins:
  - jekyll-paginate
  - jekyll-gist

